services:
  db:
    image: postgres:17-alpine
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d evolved-hackathon"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - evolved-hackathon-db-data:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=donothackmeplease
      - POSTGRES_USER=postgres
      - POSTGRES_DB=evolved-hackathon
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    networks:
      - host-network


  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - host-network

  api:
    restart: always
    entrypoint: ["/app/docker-entrypoint.sh"]
    command: sanic server:create_app --host 0.0.0.0 --port 8000
    runtime: nvidia
    environment:
      - ENV_FOR_DYNACONF=docker
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    depends_on:
      - db
      - redis
    build:
      context: ./
      args:
        USER_ID: ${UID:-1002}
        GROUP_ID: ${GID:-1002}
    extra_hosts:
      - "host.docker.internal:host-gateway" # allows container -> host
    ports:
      - "8000:8000"
    networks:
      - host-network
    volumes:
      - /home/nebius/julio/runs:/app/tmp/output/results:rw

  
volumes:
  evolved-hackathon-db-data:

networks:
  host-network:
    driver: bridge